{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "spy.serviceAccountName" . }}
  labels:
    {{- include "spy.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  automountServiceAccountToken: false
  {{- end }}



---
# Secret attach to service account 
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "spy.serviceAccountName" . }}-secret
  annotations: 
    kubernetes.io/service-account.name: {{ include "spy.serviceAccountName" . }}
type: kubernetes.io/service-account-token


---
# Define role with necesary permissions
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "spy.serviceAccountName" . }}-role
  labels:
    {{- include "spy.labels" . | nindent 4 }}
rules:
- apiGroups: [""]
  resources:
  - namespaces
  - nodes
  - services
  - endpoints
  - pods
  - nodes/proxy
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources:
  - configmaps
  verbs: ["get"]
- nonResourceURLs: ["/metrics"]
  verbs: ["get"]

---
# Binding role with service account 
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "spy.serviceAccountName" . }}-role-binding
  labels:
    {{- include "spy.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "spy.serviceAccountName" . }}-role
subjects:
- kind: ServiceAccount
  name: {{ include "spy.serviceAccountName" . }}-account
  namespace: default

{{- end -}}