# kustomization.yaml
#apiVersion: kustomize.config.k8s.io/v1beta1
#kind: Kustomization

# namespace to deploy all resources to
namespace: go-bumblebee

resources:
- ../../redis


# all with following *kustomization*

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
