apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "gate.fullname" . }}
  labels:
    {{- include "gate.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "gate.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "gate.selectorLabels" . | nindent 8 }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ include "gate.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: AIR_SERVICE_ENDPOINT
              value: airservice:9011
            - name: SPY_SERVICE_ENDPOINT
              value: spyservice:9041
          ports:
            {{- range .Values.service.ports }}
            - name: {{ .name }}
              containerPort: {{ .port }}
              protocol: TCP
            {{- end }}
          livenessProbe:
            httpGet:
              path: /ping
              {{- range .Values.service.ports }}
              {{- if eq .name "http" }}
              port: {{ .port }}
              {{- end }}
              {{- end }}
          readinessProbe:
            httpGet:
              path: /ping
              {{- range .Values.service.ports }}
              {{- if eq .name "http" }}
              port: {{ .port }}
              {{- end }}
              {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
