# kustomization.yaml
#apiVersion: kustomize.config.k8s.io/v1beta1
#kind: Kustomization

# namespace to deploy all resources to
namespace: go-bumblebee

resources:
- ns.yaml
- ../../gql


# all with following *kustomization*
images:
- name: herochinese/go-bumblebee-gql
  newName: __gql_docker_image__
  newTag: __gql_image_tag__

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
