# kustomization.yaml
#apiVersion: kustomize.config.k8s.io/v1beta1
#kind: Kustomization

# namespace to deploy all resources to
namespace: go-bumblebee

resources:
- ns.yaml
- ../../front


# all with following *kustomization*
images:
- name: herochinese/go-bumblebee-front
  newName: __fromt_docker_image__
  newTag: __front_image_tag__

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
