# kustomization.yaml
#apiVersion: kustomize.config.k8s.io/v1beta1
#kind: Kustomization

# namespace to deploy all resources to
namespace: go-bumblebee

resources:
- ns.yaml
- ../../locust


# all with following *kustomization*
images:
- name: herochinese/go-bumblebee-locust
  newName: __locust_docker_image__
  newTag: __locust_image_tag__

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
