apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: gql-gateway
spec:
  selector:
    istio: ingressgateway # use Istio default gateway implementation
  servers:
  - port:
      number: 9030
      name: http
      protocol: HTTP
    hosts:
    - "*"
