apiVersion: apps/v1
kind: Deployment 
metadata:
  name: air
spec:
  replicas: 3
  selector:
    matchLabels:
      app: air 
  template:
    metadata:
      labels: 
        app: air 
    spec:
      terminationGracePeriodSeconds: 5
      containers:
      - name: air-go-bumblebee
        image:  herochinese/go-bumblebee-air:new-combo-jazz
        env:
          - name: AQI_SERVER_URL
            valueFrom: 
              secretKeyRef:
                name: airsecret
                key: aqiUrl
          - name: AQI_SERVER_TOKEN
            valueFrom: 
              secretKeyRef:
                name: airsecret
                key: aqiToken
          - name: IP_STACK_SERVER_URL
            valueFrom: 
              secretKeyRef:
                name: airsecret
                key: ipstackUrl
          - name: IP_STACK_SERVER_TOKEN
            valueFrom: 
              secretKeyRef:
                name: airsecret
                key: ipstackToken
          - name: REDIS_SERVER_ADDRESS
            value: redis-cart:6379
        ports:
          - name: http
            containerPort: 9011
        resources:
          requests: 
            cpu: 100m
            memory: 64Mi
          limits:
            cpu: 200m
            memory: 128Mi