# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  build-gate:
    docker:
      # specify the version
      - image: circleci/golang:1.14.1

    working_directory: /go/src/github.com/cc4i/go-bumblebee
    steps:
      - checkout

      - setup_remote_docker:
          docker_layer_caching: true
          
      # specify any bash command here prefixed with `run: `
      - run: 
          name: building & test
          command: |
            which go
            echo $PATH
            cd /go/src/github.com/cc4i/go-bumblebee/src/gate
            ls -F
            go get -v -d
            go test -v -cover ./...
      - run: 
          name: building image & push
          command: |
            cd /go/src/github.com/cc4i/go-bumblebee/src/gate
            echo $DOCKER_PASS | docker login --username $DOCKER_USER --password-stdin
            docker build -t go-bumblebee/gate:$CIRCLE_BRANCH .
            docker push go-bumblebee/gate:$CIRCLE_BRANCH .
  build-air:
    docker:
      # specify the version
      - image: circleci/golang:1.14.1

    working_directory: /go/src/github.com/cc4i/go-bumblebee
    steps:
      - checkout

      # specify any bash command here prefixed with `run: `
      - run: 
          name: building & test
          command: |
            which go
            echo $PATH
            cd /go/src/github.com/cc4i/go-bumblebee/src/air
            ls -F
            go get -v -d
            go test -v -cover ./...
      
workflows:
  version: 2
  build-workflow:
    jobs:
      - build-gate
      - build-air

