apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: build-air-from-git
spec:
  params:
    - name: pathToDockerFile
      type: string
      description: The path to the dockerfile to build
      default: $(resources.inputs.docker-source.path)/Dockerfile
    - name: pathToContext
      type: string
      description: |
        The build context used by Kaniko
        (https://github.com/GoogleContainerTools/kaniko#kaniko-build-contexts)
      default: $(resources.inputs.docker-source.path)
  resources:
    inputs:
      - name: docker-source
        type: git
    outputs:
      - name: builtImage
        type: image
  steps:
    - name: build-and-push
      image: gcr.io/kaniko-project/executor:v0.17.1
      # specifying DOCKER_CONFIG is required to allow kaniko to detect docker credential
      env:
        - name: "DOCKER_CONFIG"
          value: "/tekton/home/.docker/"
      command:
        - /kaniko/executor
      args:
        - --dockerfile=$(params.pathToDockerFile)
        - --destination=$(resources.outputs.builtImage.url)
        - --context=$(params.pathToContext)
    - image: alpine/git  # contains bash
      script: |
        git version
        git status


---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: all-service
secrets:
  - name: regcred





---
apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: air-git
spec:
  type: git
  params:
    - name: revision
      value: new-combo-jazz
    - name: url
      value: https://github.com/cc4i/go-bumblebee


---
apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: air-service
spec:
  type: image
  params:
    - name: url
      value: herochinese/air-service:latest
