apiVersion: apps/v1
kind: Deployment 
metadata:
  name: locust
spec:
  selector:
    matchLabels:
      app: locust 
  template:
    metadata:
      labels: 
        app: locust 
    spec:
      terminationGracePeriodSeconds: 5
      containers:
      - name: locust-go-bumblebee
        image:  herochinese/go-bumblebee-locust:new-combo-jazz
        ports:
          - name: http
            containerPort: 8089
        resources:
          requests: 
            cpu: 200m
            memory: 128Mi
          limits:
            cpu: 800m
            memory: 512Mi
