# kustomization.yaml
#apiVersion: kustomize.config.k8s.io/v1beta1
#kind: Kustomization

# namespace to deploy all resources to
namespace: go-bumblebee

resources:
- ../../gql


# all with following *kustomization*
images:
- name: herochinese/go-bumblebee-gql
  newName: herochinese/go-bumblebee-gql
  newTag: new-combo-jazz

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
