apiVersion: argoproj.io/v1alpha1
kind: Rollout 
metadata:
  name: air-bluegreen
spec:
  replicas: 3
  selector:
    matchLabels:
      app: air-bluegreen 
  template:
    metadata:
      labels: 
        app: air-bluegreen 
    spec:
      terminationGracePeriodSeconds: 5
      containers:
      - name: air-go-bumblebee
        image:  herochinese/go-bumblebee-air:new-combo-jazz
        env:
          - name: AQI_SERVER_URL
            valueFrom: 
              secretKeyRef:
                name: airsecret
                key: aqiUrl
          - name: AQI_SERVER_TOKEN
            valueFrom: 
              secretKeyRef:
                name: airsecret
                key: aqiToken
          - name: IP_STACK_SERVER_URL
            valueFrom: 
              secretKeyRef:
                name: airsecret
                key: ipstackUrl
          - name: IP_STACK_SERVER_TOKEN
            valueFrom: 
              secretKeyRef:
                name: airsecret
                key: ipstackToken
          - name: REDIS_SERVER_ADDRESS
            value: redis-cart:6379
        ports:
          - name: http
            containerPort: 9011
        resources:
          requests: 
            cpu: 100m
            memory: 64Mi
          limits:
            cpu: 200m
            memory: 128Mi
  strategy:
    blueGreen:
      activeService: air-bluegreen-active
      previewService: air-bluegreen-preview
      autoPromotionEnabled: false

---
kind: Service
apiVersion: v1
metadata:
  name: air-bluegreen-active
spec:
  selector:
    app: air-bluegreen
  ports:
  - protocol: TCP
    port: 9011
    targetPort: 9011

---
kind: Service
apiVersion: v1
metadata:
  name: air-bluegreen-preview
spec:
  selector:
    app: air-bluegreen
  ports:
  - protocol: TCP
    port: 9011
    targetPort: 9011