# kustomization.yaml
#apiVersion: kustomize.config.k8s.io/v1beta1
#kind: Kustomization

# namespace to deploy all resources to
namespace: go-bumblebee

resources:
- ../../front


# all with following *kustomization*
images:
- name: herochinese/go-bumblebee-front
  newName: herochinese/go-bumblebee-front
  newTag: new-combo-jazz

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
