# kustomization.yaml
#apiVersion: kustomize.config.k8s.io/v1beta1
#kind: Kustomization

# namespace to deploy all resources to
namespace: go-bumblebee

resources:
- ns.yaml
- ../../air


# all with following *kustomization*
images:
- name: herochinese/go-bumblebee-air
  newName: __air_docker_image__
  newTag: __air_image_tag__

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
