version: 0.2

phases:
    pre_build:
        commands:
          - echo Logging in to Amazon ECR...
          - echo $AWS_DEFAULT_REGION
          - aws --version
          - $(aws ecr get-login --region $AWS_DEFAULT_REGION --no-include-email)
          - ACCOUNT_ID=$(aws sts get-caller-identity|jq -r '.Account')
          - DOCKER_IMAGE=herochinese/go-bumblebee-air
          - IMAGE_TAG=$CODEBUILD_SOURCE_VERSION
          - REPOSITORY_URI=$ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$DOCKER_IMAGE  
          - |
            aws ecr create-repository \
              --repository-name $DOCKER_IMAGE \
              --image-scanning-configuration scanOnPush=true \
              --region $AWS_DEFAULT_REGION || true
    build:
        commands:
          - echo Build started on `date`
          - echo Building the Docker image...
          - echo $PWD
          - cd src/air
          - make test
          - echo Building $DOCKER_IMAGE:$IMAGE_TAG...
          - docker build . -t $DOCKER_IMAGE:$IMAGE_TAG
          - echo Tagging $REPOSITORY_URI:$IMAGE_TAG...
          - docker tag $DOCKER_IMAGE:$IMAGE_TAG $REPOSITORY_URI:$IMAGE_TAG
    post_build:
        commands:
          - echo Build completed on `date`
          - echo Pushing the Docker images...
          - docker push $REPOSITORY_URI:$IMAGE_TAG
